### PR TITLE
Add PCA, CAD drawings, previous commits, and fake ML 

### PR DESCRIPTION
**Pull request by Bshortall**

### CODE REVIEW

**Comment by jonathanm-12** [comment]
Mitchell asked if you could get rid of the PNGs

**Comment by Bshortall** [comment]
they're deleted

**Review by jonathanm-12 — APPROVED** [review]

**Review by mitch-gilmore — CHANGES_REQUESTED** [review]
1. Hardware stuff looks fine, but is it up to data?
2. There are many hard paths set. Can you change them to relative ones in so the script is usable on there machines?
3. There are portions of the code that are commented or uncommented or commented for functionality. Can you look into a simple alternative such as argparse or sys.argv to address this better?
4. Are Both the gradient booster and PCA being used? meaning are all 3 files required or a some of them artifacts of exploration?

**Review by mitch-gilmore — APPROVED** [review]
Phenomenal work @Bshortall! Aproved!

**Pull request merged**
