### PR TITLE
add virtual environment and gui

### PR DESCRIPTION
**Pull request by jonathanm-12**

### CODE REVIEW

**Comment by mitch-gilmore** [comment]
What are .egg files? Are the needed for tracking or are they generated by the virtual environment script?

**Comment by jonathanm-12** [comment]
Those are used for generating the plane, barriers, and sphere inside the virtual environment. I created them using Blender. See:

```python
self.scene = generate.GenerateModel(self, (0,0,-0.5), (50,50,10), (0,0,0), self.nodepath3, "my-objects/plane.egg")
self.sphObject = generate.GenerateModel(self, (0, 10, 0.1), (0.6, 0.6, 0.6), (0,0,0), self.nodepath2, "my-objects/sphere.egg")
self.barrier1 = generate.GenerateModel(self,(0, 300, 1.63), (6.3, 31.3, 1), (90,0,0), self.nodepath1, "my-objects/barrier.egg")```

**Comment by mitch-gilmore** [comment]
Okay so they were made in Blender and then used in the Virtual Environment script?

**Comment by jonathanm-12** [comment]
@mgilmore42 thats correct

**Pull request merged**
